install:
  - npm install
script:
  - npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist/* $FTP_USER@$FTP_HOST:/the-division/

